
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = ''
_lr_action_items = {}
_lr_action = {}

_lr_goto_items = {}

_lr_goto = {}

_lr_productions = []
